"""v2 baseline: single-tenant admin + per-key-model cooldown + metric buckets

Revision ID: 31a8a6090b31
Revises: 
Create Date: 2026-05-23 02:00:50.187022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a8a6090b31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_preview', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', 'expired', name='apikeystatus', native_enum=False, length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unlimited_quota', sa.Boolean(), nullable=False),
    sa.Column('remaining_quota_usd', sa.Float(), nullable=False),
    sa.Column('used_quota_usd', sa.Float(), nullable=False),
    sa.Column('allowed_models', sa.JSON(), nullable=True),
    sa.Column('allowed_ips', sa.JSON(), nullable=True),
    sa.Column('max_tokens_per_request', sa.Integer(), nullable=False),
    sa.Column('rpm_limit', sa.Integer(), nullable=False),
    sa.Column('concurrency_limit', sa.Integer(), nullable=False),
    sa.Column('stream_enabled', sa.Boolean(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index('ix_api_keys_label', ['label'], unique=False)
        batch_op.create_index('ix_api_keys_status', ['status'], unique=False)
        batch_op.create_index('ix_api_keys_token_hash', ['token_hash'], unique=True)

    op.create_table('key_metric_buckets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upstream_key_id', sa.Integer(), nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.BigInteger(), nullable=False),
    sa.Column('completion_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('total_latency_ms', sa.BigInteger(), nullable=False),
    sa.Column('max_latency_ms', sa.Integer(), nullable=False),
    sa.Column('min_latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('key_metric_buckets', schema=None) as batch_op:
        batch_op.create_index('ix_key_metric_buckets_bucket_start', ['bucket_start'], unique=False)
        batch_op.create_index('ix_key_metric_buckets_pair', ['upstream_key_id', 'bucket_start'], unique=True)

    op.create_table('key_model_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upstream_key_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ready', 'cooldown', 'blocked', name='keymodelstatestatus', native_enum=False, length=16), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.Integer(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('backoff_level', sa.Integer(), nullable=False),
    sa.Column('next_retry_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('key_model_states', schema=None) as batch_op:
        batch_op.create_index('ix_key_model_states_cooldown', ['cooldown_until'], unique=False)
        batch_op.create_index('ix_key_model_states_pair', ['upstream_key_id', 'model_id'], unique=True)

    op.create_table('models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_name', sa.String(length=128), nullable=False),
    sa.Column('fireworks_path', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('chat', 'completion', 'embedding', 'image', 'audio', 'rerank', 'vision', 'other', name='modelcategory', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', name='modelstatus', native_enum=False, length=16), nullable=False),
    sa.Column('context_length', sa.Integer(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('input_price_per_1m', sa.Float(), nullable=False),
    sa.Column('output_price_per_1m', sa.Float(), nullable=False),
    sa.Column('cached_input_price_per_1m', sa.Float(), nullable=False),
    sa.Column('supports_streaming', sa.Boolean(), nullable=False),
    sa.Column('supports_tools', sa.Boolean(), nullable=False),
    sa.Column('supports_vision', sa.Boolean(), nullable=False),
    sa.Column('supports_reasoning', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_name')
    )
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index('ix_models_public_name', ['public_name'], unique=True)
        batch_op.create_index('ix_models_status', ['status'], unique=False)

    op.create_table('probe_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upstream_key_id', sa.BigInteger(), nullable=False),
    sa.Column('upstream_key_preview', sa.String(length=32), nullable=False),
    sa.Column('success', sa.String(length=16), nullable=False),
    sa.Column('balance_usd', sa.Float(), nullable=False),
    sa.Column('monthly_spend_limit_usd', sa.Float(), nullable=False),
    sa.Column('monthly_spend_used_usd', sa.Float(), nullable=False),
    sa.Column('suspend_state', sa.String(length=64), nullable=True),
    sa.Column('account_state', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('probe_history', schema=None) as batch_op:
        batch_op.create_index('ix_probe_history_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_probe_history_key', ['upstream_key_id'], unique=False)

    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('api_key_label', sa.String(length=64), nullable=True),
    sa.Column('upstream_key_id', sa.Integer(), nullable=True),
    sa.Column('upstream_key_preview', sa.String(length=32), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('public_model', sa.String(length=255), nullable=False),
    sa.Column('upstream_model', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('stream', sa.Boolean(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('raw_cost_usd', sa.Float(), nullable=False),
    sa.Column('billed_cost_usd', sa.Float(), nullable=False),
    sa.Column('rate_multiplier', sa.Float(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('ttft_ms', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.create_index('ix_request_logs_api_key', ['api_key_id'], unique=False)
        batch_op.create_index('ix_request_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_request_logs_request_id', ['request_id'], unique=False)
        batch_op.create_index('ix_request_logs_upstream', ['upstream_key_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('upstream_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('key_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_preview', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=128), nullable=True),
    sa.Column('account_email', sa.String(length=255), nullable=True),
    sa.Column('suspend_state', sa.String(length=64), nullable=True),
    sa.Column('account_state', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', 'auto_disabled', 'unhealthy', 'testing', name='upstreamkeystatus', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('concurrency_limit', sa.Integer(), nullable=False),
    sa.Column('rpm_limit', sa.Integer(), nullable=False),
    sa.Column('balance_usd', sa.Float(), nullable=False),
    sa.Column('monthly_spend_limit_usd', sa.Float(), nullable=False),
    sa.Column('monthly_spend_used_usd', sa.Float(), nullable=False),
    sa.Column('balance_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('total_requests', sa.BigInteger(), nullable=False),
    sa.Column('total_input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_reason', sa.String(length=128), nullable=True),
    sa.Column('backoff_level', sa.Integer(), nullable=False),
    sa.Column('success_count_24h', sa.Integer(), nullable=False),
    sa.Column('failed_count_24h', sa.Integer(), nullable=False),
    sa.Column('stability_score', sa.Float(), nullable=False),
    sa.Column('auto_disable_reason', sa.String(length=255), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('upstream_keys', schema=None) as batch_op:
        batch_op.create_index('ix_upstream_keys_account_id', ['account_id'], unique=False)
        batch_op.create_index('ix_upstream_keys_cooldown_until', ['cooldown_until'], unique=False)
        batch_op.create_index('ix_upstream_keys_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upstream_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_upstream_keys_status')
        batch_op.drop_index('ix_upstream_keys_cooldown_until')
        batch_op.drop_index('ix_upstream_keys_account_id')

    op.drop_table('upstream_keys')
    op.drop_table('system_settings')
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_request_logs_upstream')
        batch_op.drop_index('ix_request_logs_request_id')
        batch_op.drop_index('ix_request_logs_created_at')
        batch_op.drop_index('ix_request_logs_api_key')

    op.drop_table('request_logs')
    with op.batch_alter_table('probe_history', schema=None) as batch_op:
        batch_op.drop_index('ix_probe_history_key')
        batch_op.drop_index('ix_probe_history_created_at')

    op.drop_table('probe_history')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index('ix_models_status')
        batch_op.drop_index('ix_models_public_name')

    op.drop_table('models')
    with op.batch_alter_table('key_model_states', schema=None) as batch_op:
        batch_op.drop_index('ix_key_model_states_pair')
        batch_op.drop_index('ix_key_model_states_cooldown')

    op.drop_table('key_model_states')
    with op.batch_alter_table('key_metric_buckets', schema=None) as batch_op:
        batch_op.drop_index('ix_key_metric_buckets_pair')
        batch_op.drop_index('ix_key_metric_buckets_bucket_start')

    op.drop_table('key_metric_buckets')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_api_keys_token_hash')
        batch_op.drop_index('ix_api_keys_status')
        batch_op.drop_index('ix_api_keys_label')

    op.drop_table('api_keys')
    # ### end Alembic commands ###
