"""v5: model_price_catalog table

Revision ID: 607d7b1376d1
Revises: 60b0622e1426
Create Date: 2026-05-23 11:21:35.516544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607d7b1376d1'
down_revision: Union[str, None] = '60b0622e1426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_price_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.Enum('exact', 'contains', 'prefix', name='pricematchtype', native_enum=False, length=16), nullable=False),
    sa.Column('input_per_1m', sa.Float(), nullable=False),
    sa.Column('output_per_1m', sa.Float(), nullable=False),
    sa.Column('cached_input_per_1m', sa.Float(), nullable=False),
    sa.Column('per_image_usd', sa.Float(), nullable=False),
    sa.Column('per_step_usd', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('per_token', 'per_image', 'per_step', 'per_request', name='priceunit', native_enum=False, length=16), nullable=False),
    sa.Column('source', sa.Enum('seed', 'manual', 'litellm', 'fireworks', name='pricesource', native_enum=False, length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_price_catalog', schema=None) as batch_op:
        batch_op.create_index('ix_price_catalog_pattern', ['pattern'], unique=False)
        batch_op.create_index('ix_price_catalog_source', ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_price_catalog', schema=None) as batch_op:
        batch_op.drop_index('ix_price_catalog_source')
        batch_op.drop_index('ix_price_catalog_pattern')

    op.drop_table('model_price_catalog')
    # ### end Alembic commands ###
