"""v4: api_key.token_encrypted + request_log.api_key_preview

Revision ID: 60b0622e1426
Revises: 8f0d16ab3af7
Create Date: 2026-05-23 02:47:35.135168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b0622e1426'
down_revision: Union[str, None] = '8f0d16ab3af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_encrypted', sa.LargeBinary(), nullable=True))

    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key_preview', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_column('api_key_preview')

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_column('token_encrypted')

    # ### end Alembic commands ###
