"""v6: hot-path composite indexes on request_logs

Revision ID: 642784f0df90
Revises: 607d7b1376d1
Create Date: 2026-05-23 12:07:43.264816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '642784f0df90'
down_revision: Union[str, None] = '607d7b1376d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.create_index('ix_request_logs_api_key_created', ['api_key_id', 'created_at'], unique=False)
        batch_op.create_index('ix_request_logs_model_created', ['public_model', 'created_at'], unique=False)
        batch_op.create_index('ix_request_logs_status', ['status_code'], unique=False)
        batch_op.create_index('ix_request_logs_upstream_id_desc', ['upstream_key_id', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_request_logs_upstream_id_desc')
        batch_op.drop_index('ix_request_logs_status')
        batch_op.drop_index('ix_request_logs_model_created')
        batch_op.drop_index('ix_request_logs_api_key_created')

    # ### end Alembic commands ###
