"""v3: upstream_key materialized sparkline + probe fields

Revision ID: 8f0d16ab3af7
Revises: 31a8a6090b31
Create Date: 2026-05-23 02:34:03.438694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0d16ab3af7'
down_revision: Union[str, None] = '31a8a6090b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upstream_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recent_buckets_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('recent_buckets_updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_probe_ok', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_probe_ms', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_probe_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upstream_keys', schema=None) as batch_op:
        batch_op.drop_column('last_probe_at')
        batch_op.drop_column('last_probe_ms')
        batch_op.drop_column('last_probe_ok')
        batch_op.drop_column('recent_buckets_updated_at')
        batch_op.drop_column('recent_buckets_json')

    # ### end Alembic commands ###
